---
apiVersion: v1
kind: Service
metadata:
  name: {{ partName }} 
  namespace: {{ namespace }} 
spec:
  selector:
    name: {{ partName }} 
  ports:
{% for port in servicePorts %} 
    - name: {{ port.key }} 
      protocol: TCP
      port: {{ port.value }} 
      targetPort: {{ port.value }} 
{% endfor %} 